data:
  db_dir: '/DATA'
  name: 'ksxaug'
  file_format: '*.jpg'
  height: 224
  width: 224
  class_count: 2350
  grayscale: False
  normalize: False
train:
  batch_size: 64
  augment: True
  encoder_lr: 0.0001
  decoder_lr: 0.0005
model:
  embedding_dim: 512
  attention_dim: 512
  decoder_dim: 512
  dropout: 0.5
  alpha_c: 1.
